import {
  FaReact,
  FaJava,
  FaGitAlt,
  FaDocker,
  FaNodeJs,
  FaPython,
  FaAws,
} from "react-icons/fa";
import { DiMsqlServer } from "react-icons/di";
import {
  SiSpringboot,
  SiAngular,
  SiVuedotjs,
  SiHtml5,
  SiCss3,
  SiJavascript,
  SiTypescript,
  SiTailwindcss,
  SiMysql,
  SiPostgresql,
  SiMongodb,
  SiRedis,
  SiKubernetes,
  SiJenkins,
  SiGithub,
  SiPhp,
  SiKotlin,
  SiExpress,
  SiSwagger,
  SiPostman,
  SiJira,
  SiConfluence,
  SiSimpleanalytics,
  SiTableau,
  SiApachekafka,
  SiJsonwebtokens,
  SiBootstrap,
} from "react-icons/si";

export const skills = [
  { icon: FaReact, name: "React", color: "#61DAFB" },
  { icon: SiAngular, name: "Angular", color: "#DD0031" },
  { icon: SiVuedotjs, name: "Vue.js", color: "#42B883" },
  { icon: SiHtml5, name: "HTML5", color: "#E34F26" },
  { icon: SiCss3, name: "CSS3", color: "#1572B6" },
  { icon: SiJavascript, name: "JavaScript", color: "#F7DF1E" },
  { icon: SiTypescript, name: "TypeScript", color: "#3178C6" },
  { icon: SiTailwindcss, name: "TailwindCSS", color: "#06B6D4" },
  { icon: FaJava, name: "Java", color: "#E11F21" },
  { icon: SiSpringboot, name: "Spring Boot", color: "#6DB33F" },
  { icon: SiJsonwebtokens, name: "JWT", color: "#FFFFFF" },
  { icon: FaNodeJs, name: "Node.js", color: "#3C873A" },
  { icon: SiExpress, name: "Express", color: "#888888" },
  { icon: FaPython, name: "Python", color: "#3776AB" },
  { icon: SiPhp, name: "PHP", color: "#777BB4" },
  { icon: SiKotlin, name: "Kotlin", color: "#7F52FF" },
  { icon: SiMysql, name: "MySQL", color: "#4479A1" },
  { icon: SiPostgresql, name: "PostgreSQL", color: "#336791" },
  { icon: DiMsqlServer, name: "SQL Server", color: "#CC2927" },
  { icon: SiMongodb, name: "MongoDB", color: "#4DB33D" },
  { icon: SiRedis, name: "Redis", color: "#DC382D" },
  { icon: FaGitAlt, name: "Git", color: "#F05032" },
  { icon: SiGithub, name: "GitHub", color: "#181717" },
  { icon: FaDocker, name: "Docker", color: "#2496ED" },
  { icon: SiKubernetes, name: "Kubernetes", color: "#326CE5" },
  { icon: SiJenkins, name: "Jenkins", color: "#D24939" },
  { icon: FaAws, name: "AWS", color: "#FF9900" },
  { icon: SiSwagger, name: "Swagger", color: "#85EA2D" },
  { icon: SiPostman, name: "Postman", color: "#FF6C37" },
  { icon: SiJira, name: "Jira", color: "#0052CC" },
  { icon: SiConfluence, name: "Confluence", color: "#172B4D" },
  { icon: SiSimpleanalytics, name: "Power BI", color: "#F2C811" },
  { icon: SiTableau, name: "Tableau", color: "#E97627" },
  { icon: SiApachekafka, name: "Apache Kafka", color: "#231F20" },
  { icon: SiBootstrap, name: "Bootstrap", color: "#6f42c1" },
];
